.TH "PACDEF" "8" "2023\-05\-26" "pacdef v1\&.2\&.1" "Pacdef Manual"

.SH "NAME"
pacdef — multi-backend declarative package manager
.SH SYNOPSIS
.sp
\fIpacdef\fR group <subcommand>
.sp
\fIpacdef\fR package <subcommand>
.sp
\fIpacdef\fR version
.SH DESCRIPTION
Pacdef ...

.SH CONFIGURATION
.SH SUBCOMMANDS
.SH EXIT STATUS
.SH FILES
.SH BUGS
.SH AUTHORS
.SH SEE ALSO

