name: check

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'devel'
    paths:
      - 'crates/**.rs'
      - 'crates/**/Cargo.toml'
      - 'Cargo.*'
      - "clippy.toml"
  pull_request:
    branches:
      - 'main'
      - 'devel'
    paths:
      - 'crates/**.rs'
      - 'crates/**/Cargo.toml'
      - 'Cargo.*'
      - "clippy.toml"

env:
  CARGO_TERM_COLOR: always

jobs:

  test:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: Install Packages
        run: pacman -Syu git rust clang gcc libarchive pkgconf apt --noconfirm --needed

      - name: Checkout
        uses: actions/checkout@v3

      - name: Format
        if: '!cancelled()'
        run: cargo fmt -- --check

      - name: Build
        if: '!cancelled()'
        run: cargo build --locked --features arch,debian

      - name: Clippy
        if: '!cancelled()'
        run: cargo clippy --features arch,debian -- -Dwarnings

      - name: Test
        if: '!cancelled()'
        run: cargo test --workspace --features arch,debian

  smoke_test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/archlinux/archlinux:base-devel
    steps:
    - name: Install dependencies
      run: pacman -Syyu --noconfirm rust git zsh
    - uses: actions/checkout@master
    - name: Build
      run: cargo build --features arch
